name: Python CI/CD

# Trigger on push and pull request to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
    # Step 1: Checkout code
    - uses: actions/checkout@v3

    # Step 2: Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest black pylint

    # Step 4: Set PYTHONPATH
    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    # Step 5: Run linter
    - name: Run pylint
      run: make check

    # Step 6: Run code formatter check
    - name: Run black check
      run: black --check .

    # Step 7: Run tests
    - name: Run tests
      run: |
        export PYTHONPATH=$(pwd)
        pytest -v tests/

    # Optional Step 8: Build Docker image if lint passes
    - name: Build Docker
      if: success()  # Only if previous steps succeeded
      run: docker build -t ml_project:latest .

